import os
import shutil
import time

emailMap = {
"zhonghua.zhu@nokia-sbell.com": "朱忠华",
"zhijian.huang.ext@nokia.com": "黄智坚",
"zhihua.xie@nokia-sbell.com": "谢志华",
"zhenping.gong@nokia-sbell.com": "龚真平",
"zhennan.yang@nokia-sbell.com": "杨振楠",
"zhangchuan.wang@nokia-sbell.com": "王章川",
"zeyun.yan@nokia-sbell.com": "严泽云",
"yunqiang.feng@nokia-sbell.com": "俸云强",
"yun.5.chen@nokia.com": "陈云",
"yueming.feng.ext@nokia-sbell.com": "冯玥明",
"yuan.yuan@nokia-sbell.com": "袁源",
"yuan.p.li@nokia-sbell.com": "李远平",
"yu.1.tian@nokia-sbell.com": "田宇",
"yongxia.cai@nokia-sbell.com": "蔡永霞",
"yongan.huang.ext@nokia.com": "黄永安",
"yong.2.liu.ext@nokia-sbell.com": "刘勇",
"yingxi.yao@nokia-sbell.com": "姚颖熹",
"ying.1.zou@nokia-sbell.com": "邹颖",
"yifan.1.yang@nokia-sbell.com": "杨一帆",
"yh.wang@nokia.com": "王益辉",
"yao.xie@nokia.com": "谢尧",
"yanjie.zhao@nokia-sbell.com": "赵燕杰",
"yan.yin@nokia-sbell.com": "殷彦",
"yan.9.li@nokia.com": "李彦",
"xuming.cheng@nokia-sbell.com": "程绪明",
"xuantao.luo@nokia-sbell.com": "罗宣桃",
"xu.pan@nokia-sbell.com": "潘旭",
"xu.1.lu@nokia-sbell.com": "卢旭",
"xiyin.liang.ext@nokia-sbell.com": "梁曦尹",
"xinyu.1.zhao.ext@nokia-sbell.com": "赵鑫雨",
"xingkuan.li.ext@nokia-sbell.com": "李兴宽",
"xin.jia.ext@nokia-sbell.com": "贾鑫",
"xin.5.li@nokia-sbell.com": "李欣",
"xiaoyang.tang@nokia.com": "汤小阳",
"xiaomei.ren@nokia-sbell.com": "任小梅",
"xiaojun.2.zhong.ext@nokia-sbell.com": "钟潇俊",
"xiaohong.zhang@nokia-sbell.com": "张晓宏",
"xiaofang.1.wang.ext@nokia.com": "王晓芳",
"xiaodong.1.yang@nokia-sbell.com": "杨晓东",
"xiaobing.deng@nokia-sbell.com": "邓小兵",
"xia.yang.ext@nokia.com": "杨霞",
"woody.liu@nokia-sbell.com": "刘桂青",
"wenpeng.zhu.ext@nokia-sbell.com": "朱文鹏",
"wenjuan-wendy.wang@nokia-sbell.com": "王文娟",
"wendy.w.wang@nokia-sbell.com": "王昱文",
"weihua.peng@nokia-sbell.com": "彭伟华",
"weifei.hu@nokia-sbell.com": "胡卫飞",
"wei.xia.ext@nokia-sbell.com": "夏伟",
"wei.2.wang.ext@nokia-sbell.com": "王伟",
"volan.shu@nokia.com": "舒华",
"vera.yu@nokia-sbell.com": "余音知",
"vanessa.fan@nokia-sbell.com": "范登华",
"tony.gong@nokia-sbell.com": "龚文杰",
"tong.1.wu.ext@nokia.com": "吴桐",
"tingyong.li@nokia-sbell.com": "李廷勇",
"ting.3.ye@nokia.com": "叶廷",
"ting.1.wu.ext@nokia-sbell.com": "吴婷",
"tiezhu.wang@nokia.com": "王铁柱",
"tian.yin@nokia-sbell.com": "尹甜",
"terry.yang.ext@nokia-sbell.com": "杨挺",
"taifu.luo.ext@nokia-sbell.com": "罗太富",
"swift.huang@nokia-sbell.com": "黄玉贵",
"sweety.zou@nokia-sbell.com": "邹姣",
"sophie.tang@nokia.com": "唐晓芬",
"shuwen.yi.ext@nokia-sbell.com": "易书文",
"shuo.wang@nokia-sbell.com": "王硕",
"shouhe.chen.ext@nokia-sbell.com": "陈寿和",
"shiwei.su@nokia-sbell.com": "苏世蔚",
"shirley.yang@nokia.com": "杨坤",
"sherry.xu@nokia-sbell.com": "徐小彦",
"shanli.yan@nokia-sbell.com": "严善礼",
"sandy.hu@nokia-sbell.com": "胡霞",
"samuel.shi@nokia.com": "石洪山",
"samuel.1.zhang@nokia-sbell.com": "张波",
"sam.zhang@nokia.com": "张虎",
"sabrina.sun@nokia-sbell.com": "孙南",
"ruojun.luo@nokia-sbell.com": "罗若筠",
"roy.zhang@nokia-sbell.com": "章小龙",
"ronny.1.ren@nokia-sbell.com": "任林",
"roc.zou@nokia.com": "邹鹏",
"robby.zhang@nokia-sbell.com": "张勇",
"ray.zhao@nokia-sbell.com": "赵锐",
"ran.jing@nokia-sbell.com": "井然",
"quanfen.ding.ext@nokia-sbell.com": "丁全芬",
"qiyin.chen@nokia-sbell.com": "陈麒尹",
"qingquan.luo.ext@nokia.com": "罗清泉",
"qing.hu.ext@nokia-sbell.com": "胡情",
"prince.rong@nokia-sbell.com": "荣凡",
"peter.1.lin.ext@nokia-sbell.com": "林宗举",
"pengfei.1.li.ext@nokia.com": "李鹏霏",
"peng.liu.ext@nokia-sbell.com": "刘鹏",
"peng.1.liu.ext@nokia.com": "刘鹏",
"peilun.li@nokia.com": "李沛伦",
"paul.xu@nokia.com": "徐青",
"owen.ou_yang@nokia-sbell.com": "欧阳怡彪",
"olivia.li.ext@nokia.com": "李晓飞",
"nancy.liu@nokia-sbell.com": "刘婷婷",
"na.zhao.ext@nokia-sbell.com": "赵娜",
"myer.li@nokia-sbell.com": "黎明",
"minghui.1.li@nokia-sbell.com": "李明辉",
"ming.5.zhang.ext@nokia-sbell.com": "张铭",
"mike.lv@nokia-sbell.com": "吕剑",
"michelle.pan@nokia-sbell.com": "潘佳异",
"michael.1.zhang@nokia.com": "张毅",
"meng.luo@nokia-sbell.com": "罗梦",
"maoping.tian@nokia-sbell.com": "田茂平",
"mandy.zhu@nokia-sbell.com": "朱曼",
"mandy.xie@nokia-sbell.com": "谢敏",
"mak.ma@nokia-sbell.com": "马洪波",
"lyne.he@nokia.com": "何莉",
"lucy.zhao@nokia-sbell.com": "赵白梅",
"lizhi.geng@nokia-sbell.com": "耿立直",
"liu.liu@nokia-sbell.com": "刘流",
"liqiang.song@nokia-sbell.com": "宋立强",
"liqiang.lei@nokia-sbell.com": "雷利强",
"lin.c.zhang@nokia-sbell.com": "张林聪",
"lily.guo@nokia-sbell.com": "郭莉莉",
"lillian.deng@nokia-sbell.com": "邓丽",
"lijuan.cheng@nokia-sbell.com": "程丽娟",
"liao.lin.ext@nokia-sbell.com": "廖林",
"liangwen.tang.ext@nokia-sbell.com": "唐靓雯",
"liang.1.li.ext@nokia-sbell.com": "李亮",
"li.xiang@nokia-sbell.com": "向黎",
"lewis.liu.ext@nokia-sbell.com": "刘显福",
"lei.duan.ext@nokia-sbell.com": "段磊",
"lei.an.ext@nokia-sbell.com": "安磊",
"lei.4.shi@nokia-sbell.com": "石磊",
"lawrence.luo@nokia-sbell.com": "罗云",
"larry.wu@nokia-sbell.com": "吴海霄",
"larry.liu@nokia-sbell.com": "刘远清",
"kun.zhang@nokia-sbell.com": "张琨",
"kui.xiong@nokia.com": "熊馗",
"ke.h.li.ext@nokia-sbell.com": "李可",
"junlin.li@nokia-sbell.com": "李俊霖",
"joseph.wu@nokia.com": "伍俊洪",
"jonathan.wu@nokia-sbell.com": "吴聪",
"joey.an@nokia-sbell.com": "安秋雨",
"joan.zhang@nokia-sbell.com": "张琼",
"jk.dong@nokia-sbell.com": "董健康",
"jinxin.liu@nokia-sbell.com": "刘今心",
"jing.ping@nokia-sbell.com": "平静",
"jing.3.chen.ext@nokia-sbell.com": "陈静",
"jing.2.hu.ext@nokia-sbell.com": "胡婧",
"jin.1.zhang@nokia-sbell.com": "张劲",
"jin.1.li.ext@nokia-sbell.com": "李进",
"jihua.zhao@nokia-sbell.com": "赵继华",
"jie.1.tan@nokia-sbell.com": "谭杰",
"jiao.yang@nokia-sbell.com": "杨浇",
"jianguo.xie@nokia-sbell.com": "谢键国",
"jian.11.li@nokia-sbell.com": "李建",
"jian.1.fu@nokia-sbell.com": "傅剑",
"jiahui.sun@nokia-sbell.com": "孙嘉辉",
"ji.1.zhang@nokia.com": "张季",
"jessie.yan@nokia-sbell.com": "颜吉平",
"jessica.1.zhou@nokia-sbell.com": "周节",
"jerry.z.zhang@nokia.com": "张启忠",
"jenna.ran@nokia-sbell.com": "冉静",
"jeffrey.liu@nokia-sbell.com": "刘建",
"jeffrey.li@nokia-sbell.com": "李华明",
"jeff.1.huang@nokia-sbell.com": "黄艳军",
"jason.wu@nokia-sbell.com": "吴航海",
"jason.1.yuan@nokia-sbell.com": "袁韬",
"jane.y.zhang@nokia-sbell.com": "张佳奕",
"jane.liu@nokia-sbell.com": "刘涛",
"jack.you@nokia.com": "游中军",
"jack.huang@nokia-sbell.com": "黄亭宇",
"jack.deng@nokia-sbell.com": "邓光华",
"ivy.1.wang@nokia-sbell.com": "王菁菁",
"irene.zeng@nokia-sbell.com": "曾贞",
"huijun.yang.ext@nokia-sbell.com": "杨惠钧",
"huifang.liu@nokia-sbell.com": "刘慧芳",
"hui.yuan.ext@nokia.com": "袁辉",
"hui.2.zhong.ext@nokia-sbell.com": "钟辉",
"hua.sun@nokia-sbell.com": "孙华",
"hongwei.kuang@nokia.com": "匡宏微",
"hong.shi@nokia.com": "石洪",
"hong.1.yu@nokia-sbell.com": "于洪",
"holly.hou@nokia.com": "厚立群",
"hengguo.gao.ext@nokia-sbell.com": "高恒国",
"heng.yang@nokia-sbell.com": "杨恒",
"heather.hu@nokia-sbell.com": "胡琴",
"he.peng@nokia-sbell.com": "彭贺",
"hao.5.chen.ext@nokia-sbell.com": "陈豪",
"hang.li@nokia-sbell.com": "李航",
"han.1.xiao@nokia-sbell.com": "肖翰",
"haitao.chen@nokia-sbell.com": "谌海涛",
"haijun.1.chen@nokia-sbell.com": "陈海军",
"guoyi.wang.ext@nokia-sbell.com": "王国义",
"guiqing.lin.ext@nokia-sbell.com": "林贵清",
"gong.yuan@nokia-sbell.com": "袁功",
"gerald.yu@nokia-sbell.com": "余港",
"frank.2.liu@nokia-sbell.com": "刘坚",
"frances.yu@nokia-sbell.com": "余帆",
"fei.tang@nokia-sbell.com": "唐菲",
"fei.cheng@nokia-sbell.com": "程飞",
"fei.8.wang@nokia-sbell.com": "王飞",
"fan.5.yang@nokia-sbell.com": "杨帆",
"eva.huang@nokia.com": "黄爱华",
"eric.gou@nokia-sbell.com": "苟勇刚",
"ellen.zhao@nokia-sbell.com": "赵华",
"eagle.1.wang@nokia-sbell.com": "王刘莹",
"dinjun.liu.ext@nokia-sbell.com": "刘定俊",
"di.zhou.ext@nokia-sbell.com": "周迪",
"deming.yuan@nokia-sbell.com": "袁德明",
"david.guo@nokia-sbell.com": "郭从松",
"danny.ma@nokia.com": "马征",
"dandan.1.wu@nokia-sbell.com": "武丹丹",
"dan.gou.ext@nokia-sbell.com": "苟丹",
"dan.cao.ext@nokia-sbell.com": "曹丹",
"crystal.liu.ext@nokia-sbell.com": "刘意",
"coolbee.rao@nokia-sbell.com": "饶娟",
"chunli.wang.ext@nokia-sbell.com": "王春丽",
"chunle.liu@nokia.com": "刘春乐",
"chuan.1.li.ext@nokia-sbell.com": "李川",
"chris.m.zhang@nokia-sbell.com": "张晓妹",
"chris.luo@nokia-sbell.com": "罗涛",
"chengwei.chu@nokia-sbell.com": "楚成伟",
"cheng.1.yu@nokia-sbell.com": "余成",
"chenchen.xie.ext@nokia-sbell.com": "谢辰晨",
"chaowen.xiang.ext@nokia-sbell.com": "项朝文",
"chao.yang@nokia.com": "杨超",
"chang.1.tan@nokia-sbell.com": "谭畅",
"cesc.yi@nokia-sbell.com": "易宗伟",
"cejian.zeng.ext@nokia-sbell.com": "曾测荐",
"caiyun.zhang@nokia-sbell.com": "张彩云",
"caimao.feng@nokia-sbell.com": "冯才茂",
"bruce.1.huang@nokia-sbell.com": "黄文强",
"bo.yan.ext@nokia-sbell.com": "燕波",
"bill.k.huang@nokia-sbell.com": "黄庆奎",
"bihong.he@nokia-sbell.com": "何碧宏",
"betty.zheng@nokia-sbell.com": "郑清文",
"betsy.hui@nokia-sbell.com": "李慧",
"andy.j.wu@nokia-sbell.com": "伍健晖",
"alice.liang@nokia-sbell.com": "梁洁",
"alexander.zhang@nokia-sbell.com": "章达",
"ada.ding@nokia-sbell.com": "丁莹",
"siyuan.a.zhang@nokia-sbell.com": "张思源",
}

source_dir = "D:\\2nd\\"
dest_dir = "C:\\temp\\cards\\"

def getParts(name):
    x = name.rfind(".")
    if x < 0:
        return ""
    ext = name[x:].lower()
    pre = name[:x].lower()
    return pre

counter = 0
misMatchCounter = 0
misMatchEmailList = []
for item in os.listdir(source_dir):
    email = getParts(item)
    if email.lower() in emailMap:
        counter = counter + 1
        newName = emailMap[email].strip() + "_" + item
        print(email, "=>", emailMap[email].strip(), newName)
        shutil.copyfile(source_dir + item, dest_dir + newName)
    else:
        misMatchCounter = misMatchCounter + 1
        misMatchEmailList.append(email.lower())


print ("the total number of matched emails is " + str(counter))
if (len(misMatchEmailList) > 0):
    print ("the following emails could not found")
    for email in misMatchEmailList:
        print (email)


fileName = "chEnchen.xie.ext@nokia-sbell.com.jpg"
pass
